[workspace]
authors = ["Derrick <derrick.allen1729@gmail.com>"]
channels = ["conda-forge"]
name = "algo-forex-trading"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pandas = ">=2.3.1,<3"
numpy = ">=2.3.2,<3"
plotly = ">=6.2.0,<7"
matplotlib = ">=3.10.3,<4"
xlsxwriter = ">=3.2.5,<4"
jupyter = ">=1.1.1,<2"
jupyterlab = ">=4.4.5,<5"
